### ISSUE TITLE
Cant view splats generated from NerfStuidio/Spectacular AI

### ISSUE THREAD

**Issue by rowellz** [nerfstudio-project/gsplat#101]
I have a pipeline where I train and output a .ply file with NerfStudio, and convert it to a .splat file with SpectacularAI point-cloud-tools. I am able to upload and inspect the .splat file on other web viewers like https://niujinshuchong.github.io, but the initial camera is always way off. I am hosting the .splat files from my own REST api, and they successfully load into the gsplat client, however i am always greeted with a black screen and cant find the splat no matter how hard  I try to re-orient myself. Any help or advice here would  be amazing!

**Comment by GuitarYourself** [comment]
i encountered the same problem, how do you solve this?
