### ISSUE TITLE
OptiX support?

### ISSUE THREAD

**Issue by pwais** [nerfstudio-project/gsplat#103]
Looks like UC Davis group has at least tried it: https://github.com/owensgroup/optix_splats

In theory OptiX might provide better tensor core / RT core utilization on nvidia cards, tho that could also depend on low-level (proprietary) details of nvidia OptiX.

Besides the above cited repo, is there any effort for e.g. nerfstudio gsplat to benchmark if OptiX might indeed be faster than current CUDA impl?

**Comment by vye16** [comment]
We don't have any current efforts on OptiX support -- it would be interesting to know if this would help at all, although it's unclear whether OptiX optimizations for ray-tracing would translate for splatting.
