### ISSUE TITLE
Cuda crashes when number of intersection is 0

### ISSUE THREAD

**Issue by njin19** [nerfstudio-project/gsplat#107]
There is a cuda crash when the number of intersection is 0, with the following error message. This can be reproduced in the [simple_trainer.py](https://github.com/nerfstudio-project/gsplat/blob/main/examples/simple_trainer.py) by i) setting the view matrix to all 0s, or ii) by setting the quaternion initialization to all 0s.

While both are invalid scene setups, they should be handled more gracefully, since there are use cases where the values are predicted by network outputs instead of hand-initialized or passed in.

```
out_img = RasterizeGaussians.apply(
 File "/usr/local/lib/python3.10/dist-packages/torch/autograd/function.py", line 539, in apply 
 return super().apply(*args, **kwargs) # type: ignore[misc] 
 File "/usr/local/lib/python3.10/dist-packages/gsplat/rasterize.py", line 97, in forward 
 out_img, final_Ts, final_idx = _C.rasterize_forward( 
 File "/usr/local/lib/python3.10/dist-packages/gsplat/cuda/__init__.py", line 9, in call_cuda 
 return getattr(_C, name)(*args, **kwargs)
RuntimeError: CUDA error: invalid configuration argument
```

**Comment by maturk** [comment]
@njin19 that is true, this is a problem. Simple trainer directly calls the Cuda bindings, which is actually outdated and not recommended. The new api wraps the python bindings into python functions instead, so perhaps this could be more gracefully solved there (i.e. on the python side). Just some thoughts...

**Comment by kerrj** [comment]
Closing this because of #109
