### ISSUE TITLE
Just single Pixel rendering

### ISSUE THREAD

**Issue by pknmax** [nerfstudio-project/gsplat#108]
Hello @vye16, @liruilong940607, @kerrj,
Is it possible to render just single pixel which returns the color of each single ray from different colmap camera positions using gsplat?

I am interested in getting final color at particular location for different view directions, by providing GS pointcloud, colmap camera poses, "location of target pixel for tracking in first fully rasterized image using first colmap camera pose from colmap pose sequence" or "3D location in scene (how to find it?)".

**Comment by hariharan1412** [comment]
Hey Hi again, are you able to achive this ?

**Comment by liruilong940607** [comment]
Hey. I'm not sure what is the actual need here. If you want to get the rendering for a particular pixel, is there anything preventing you from rendering a image and get the pixel color from it?

**Comment by liruilong940607** [comment]
Ah I see. The current master does not support that because everything is fused in CUDA. 

However, we are working on an upgrade to the CUDA backend in this PR #172, where a pure python implementation is support so that you can easily get that information. In the code below we are accumulating all Gaussians that contribute to each pixel in Python:

https://github.com/nerfstudio-project/gsplat/blob/f4d455e63df0282612aa852a28c3803778f7bd08/gsplat/experimental/cuda/_torch_impl.py#L267-L282

**Comment by hariharan1412** [comment]
Thank you so much ❤️ I'll look into it.

**Comment by hariharan1412** [comment]
> Ah I see. The current master does not support that because everything is fused in CUDA.
> 
> However, we are working on an upgrade to the CUDA backend in this PR #172, where a pure python implementation is support so that you can easily get that information. In the code below we are accumulating all Gaussians that contribute to each pixel in Python:
> 
> https://github.com/nerfstudio-project/gsplat/blob/f4d455e63df0282612aa852a28c3803778f7bd08/gsplat/experimental/cuda/_torch_impl.py#L267-L282
> 
> If you are in a hurry need then you can just fetch that PR and use it. The PR itself is already seriously verified. Just we are thinking a best way of merging it without too much of interrupt on the master

I'm facing issues while I'm trying to run the example script alone 

```
Traceback (most recent call last):
  File "example.py", line 33, in <module>
    from nerfdata.dataset.colmap.dataset import Dataset
ModuleNotFoundError: No module named 'nerfdata'
```

could you please help me solve this ?

**Comment by liruilong940607** [comment]
That is a dependence we are not open-source yet. 

So that means the script in this PR is not directly executable. As I mentioned above, we are figuring out the best way of merging it in without outsourced dependence. 

However it should be fairly easy to swap our `nerfdata` with your own data parser -- it is simply just for parsing a colmap capture.

**Comment by hariharan1412** [comment]
Thanks for your reply. I'm working on it, and in the meantime, I have a small doubt: is there any ```render.py``` available in Gsplat like in '''graphdeco-inria''' where I can render the splats directly once the model is trained entirely so I can debug and modify code easily?

**Comment by liruilong940607** [comment]
If what you are looking for is a minimal script only to render a splat, we don't have it yet but we will add it together with that PR soon.

But it should not be very hard to create one quickly from that standalone example script in this PR.

**Comment by hariharan1412** [comment]
Thanks for your help, but I'm new to the Nerfstudio codebase, so could you please help me with how I can pass transforms.json instead of nerfdata, or please tell me what K is from the dataset so I can modify it and pass it. 

```
dataset = Dataset(data_dir=f"data/360_v2/{args.scene}/", factor=8, normalize=True)

    # preload
    images = np.stack(
        [imageio.imread(image_path)[..., :3] for image_path in dataset.image_paths]
    )
    images = torch.from_numpy(images).float().to(device) / 255.0
    c2ws = torch.from_numpy(dataset.camtoworlds).float().to(device)
    K = torch.from_numpy(dataset.K).float().to(device)
    points = torch.from_numpy(dataset.points).float()
    points_rgb = torch.from_numpy(dataset.points_rgb).float()
    n_images, height, width = images.shape[:3]
    ```
    
  what is ``` K ``` here ? Thank you.

**Comment by hariharan1412** [comment]
Thank 

> Ah I see. The current master does not support that because everything is fused in CUDA.
> 
> However, we are working on an upgrade to the CUDA backend in this PR #172, where a pure python implementation is support so that you can easily get that information. In the code below we are accumulating all Gaussians that contribute to each pixel in Python:
> 
> https://github.com/nerfstudio-project/gsplat/blob/f4d455e63df0282612aa852a28c3803778f7bd08/gsplat/experimental/cuda/_torch_impl.py#L267-L282
> 
> If you are in a hurry need then you can just fetch that PR and use it. The PR itself is already seriously verified. Just we are thinking a best way of merging it without too much of interrupt on the master

Thank you for your work. I was successfully able to train the model and I have one doubt about where you are calling this ```accumulate()``` in your code. I read your code, but I don't think you are calling it anywhere, so could you please tell me where to use this function exactly?

**Comment by liruilong940607** [comment]
That's used in this function:

https://github.com/nerfstudio-project/gsplat/blob/f4d455e63df0282612aa852a28c3803778f7bd08/gsplat/experimental/test.py#L303-L305

Which is a exact substitute of the `rendering` function. 

Note that if you call `_rendering` function, you should expect much higher memory usages and much slower speed as it is running rasterization in pure python. That's just the price have to pay in exchange for flexibility

**Comment by hariharan1412** [comment]
When the training is happening, I clearly see that rasterization is happening; however, when I try to run the rasterization alone, I keep ending up with a big, plain single-color image. Could you please help me? 

rendering Script :
```
def test_rasterize_to_pixels():
      from gsplat.experimental.cuda import _rendering, 
      data_path = "results/splatfacto_model_data.npz"
  
      data = np.load(data_path)  # 3 cameras
      height, width = data["height"].item(), data["width"].item()
      viewmats = torch.from_numpy(data["viewmats"]).to(device)
      Ks = torch.from_numpy(data["Ks"]).to(device)
  
      means = torch.from_numpy(data["means3d"]).to(device)
      
      scales = torch.from_numpy(data["scales"]).to(device) * 0.1 + 0.1
  
      quats = torch.from_numpy(data["quats"]).to(device) 
          
      opacities = torch.from_numpy(data["opacities"]).to(device) 
      opacities = opacities.squeeze()
  
      
      Ks = torch.tensor([[320.0, 0.0, 320.0],
                         [0.0, 320.0, 320.0],
                         [0.0, 0.0, 1.0]]).unsqueeze(0).to(device=device)  # Single camera matrix
      N = data["viewmats"].shape[0]  # Assuming viewmats is [C, 4, 4]
      Ks = Ks.repeat(N, 1, 1)  
  
  
      colors = torch.from_numpy(data["colors"]).to(device)
      colors = colors.unsqueeze(0).repeat(N, 1, 1)
  
  
      print(colors.shape)
      C = len(Ks)
  
      viewmats.requires_grad = True
      quats.requires_grad = True
      scales.requires_grad = True
      means.requires_grad = True
  
  
  
      render_colors, render_alphas = _rendering(
          means, quats, scales, opacities, colors, viewmats, Ks, width, height
      )
      
      return render_colors, render_alphas
      
 render_colors, render_alphs = test_rasterize_to_pixels()
```
   
But when I plot the render_colors, I end up with the same color on all pixels.
   
   
![image](https://github.com/nerfstudio-project/gsplat/assets/51135395/d1cbe27c-6204-4328-b12d-fd62c8552f0c)

**Comment by liruilong940607** [comment]
You probably don't want `*0.1+0.1` in this line if you have a trained model already.
`scales = torch.from_numpy(data["scales"]).to(device) * 0.1 + 0.1`

**Comment by hariharan1412** [comment]
Yeah, I changed that, but still, I'm facing the same issue. Could you please tell me how I can pass my own camera extrinsic from transforms? json, when I try to load it, it shows grad_fn is required, so I tried gradient = true, false, and still I can't pass my own camera extrinsic. So far, I'm passing dummy.

**Comment by abrahamezzeddine** [comment]
> Ah I see. The current master does not support that because everything is fused in CUDA.
> 
> However, we are working on an upgrade to the CUDA backend in this PR #172, where a pure python implementation is support so that you can easily get that information. In the code below we are accumulating all Gaussians that contribute to each pixel in Python:
> 
> https://github.com/nerfstudio-project/gsplat/blob/f4d455e63df0282612aa852a28c3803778f7bd08/gsplat/experimental/cuda/_torch_impl.py#L267-L282
> 
> If you are in a hurry need then you can just fetch that PR and use it. The PR itself is already seriously verified. Just we are thinking a best way of merging it without too much of interrupt on the master

@liruilong940607 Thank you for your great work. I am wondering if this something it will do, or information that will be possible to get? From another thread, I asked for this but I do not think the community knows this yet as it might yet to be implemented. But as I read this, it seems that this will be supported soon with this PR? See below comment if that will solve it;

> With COLMAP, it is possible to extract data to determine which images and keypoints correspond to specific 3D points and to identify which images have been matched.
> 
> I am wondering if it is possible to track which Gaussian splats correspond to which keypoints, along with their associated image files and pixel coordinates via some sort of index? Is there a way to "tap" into the code to keep track of this when using Nerfstudio/GSplat?
> 
> Specifically, I want to identify the originating image and pixel coordinate for each Gaussian splat (with respect to the gaussian splatted point cloud). While COLMAP provides this information for 3D points, I would like to know if it is possible to extend this tracking to the exported PLY file for the splats.

I've created a script for COLMAP that consolidates the points3d.bin, camera.bin, and images.bin files into a single file. This simplifies the interpretation of data, clarifying contributions to pixel coordinates, image filenames, and their indices.

Example such as below;

> POINT3D_ID 3D_X 3D_Y 3D_Z R G B POINT2D_IDX PIXEL_X PIXEL_Y IMAGE_ID IMAGE_NAME
> 1054 -2.2514710427743658 0.34472229191518061 -0.31922396259922448 169 167 142 2166 2189.711181640625 2253.42578125 83 IMG_2692.JPG
> 1054 -2.2514710427743658 0.34472229191518061 -0.31922396259922448 169 167 142 3340 2936.756103515625 2486.4677734375 85 IMG_2694.JPG
> 1054 -2.2514710427743658 0.34472229191518061 -0.31922396259922448 169 167 142 2382 367.91998291015625 2102.93994140625 80 IMG_2689.JPG
> 446883 3.5806275984290243 0.52853412315400827 2.527234807406364 193 188 168 7873 3242.96533203125 2536.799072265625 262 IMG_2871.JPG
> 446883 3.5806275984290243 0.52853412315400827 2.527234807406364 193 188 168 7991 2603.289794921875 2463.16650390625 263 IMG_2872.JPG

I am looking to do the same with GSplat, if possible.

**Comment by liruilong940607** [comment]
Hi @abrahamezzeddine, the splitting of the Gaussians are control on the python side, not CUDA, so it should be very doable to track the IDs of the GSs by hacking the python code.

**Comment by abrahamezzeddine** [comment]
> Hi @abrahamezzeddine, the splitting of the Gaussians are control on the python side, not CUDA, so it should be very doable to track the IDs of the GSs by hacking the python code.

Hello @liruilong940607 
Could you please guide me a little bit? I am not very familiar with the GSplat Code in general, so a little push in the right direction and I should be able to do the rest, hopefully. :)

**Comment by liruilong940607** [comment]
Gsplat repo will have a big update very soon, in which we will put a standalone training script in. For now I could only point you to the nerfstudio repo.

The splitting & cloning & pruning is happening here in nerfstudio's implementation.

https://github.com/nerfstudio-project/nerfstudio/blob/742963e07369b70912b786a100e94c98dec1b742/nerfstudio/models/splatfacto.py#L439-L494

So I guess what you want is to maintain a tensor storing the initial IDs, and split/clone/prune that tensor together with all other attributes of GS.

**Comment by pknmax** [comment]
@hariharan1412 are you able to achieve this? how to do it using original 3D-GS?

**Comment by hariharan1412** [comment]
Could you explain your question more in detail? as you can see, we discussed lot of things here, so please be more specific about what you are asking

**Comment by pknmax** [comment]
> Could you explain your question more in detail? as you can see, we discussed lot of things here, so please be more specific about what you are asking
I am talking about this:
Is it possible to render just single pixel which returns the color of each single ray from different colmap camera positions using gsplat?
> 
> I am interested in getting final color at particular location for different view directions, by providing GS pointcloud, colmap camera poses, "location of target pixel for tracking in first fully rasterized image using first colmap camera pose from colmap pose sequence" or "3D location in scene (how to find it?)".

**Comment by hariharan1412** [comment]
Yes I can, 
refer this : https://github.com/nerfstudio-project/gsplat/issues/180#issue-2306505326

**Comment by pknmax** [comment]
hello @liruilong940607,

thanks for the great update to gsplat.
how can I use accumulate() in your [fork](https://github.com/liruilong940607/gaussian-splatting)?
how can I update that code?
Thanks.

**Comment by liruilong940607** [comment]
Hi @pknmax 

I just added a function `_rasterization()` to the latest main branch, which aligns with the `rasterization()` function (with a few advanced arguments not supported) but uses the `accumulate()` function to render the image. So you can easily swap 
between the two.

https://github.com/nerfstudio-project/gsplat/blob/56f186749edf500fbd023b4b73cd82beef17de3a/gsplat/rendering.py#L406

**Comment by pknmax** [comment]
Hi @liruilong940607,
does this `_rasterization() `approach takes  20+hrs instead of 20/25 min for optimization?

**Comment by liruilong940607** [comment]
yes because its fully pytorch implementation (no CUDA kernel fusion).

**Comment by pknmax** [comment]
@liruilong940607 can we use `rasterize_to_indices_in_range()` and `accumulate()` with optimized gaussians ply file by `rasterization() ` approach and track a pixel for different camera poses?

**Comment by liruilong940607** [comment]
Yes these functions are perfectly aligned. In fact we were using `rasterize_to_indices_in_range()` and `accumulate()` to test our CUDA implementation of `rasterization()`

**Comment by pknmax** [comment]
@liruilong940607 I tied using `_rasterize_to_pixels` with optimized gaussians ply file by` rasterization()`, which in-turn uses `rasterize_to_indices_in_range() `and a`ccumulate()`
 ; but just getting black/empty image (..../aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [7,0,0], thread: [16,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed...)
  
    ```
ply_file_path = "/work/3DGSoutput/struct_color_taylor_primaries_plyaug_gsplat_extended/point_cloud/taylor_swift_extended_cropped.ply"
    colmap_path = "/work/3DGSdatasets/struct_color_taylor_primaries/" 
    
    print("Loading PLY file...")
     # Loading ply files
    pc = GaussianModel(sh_degree=3)
    pc.load_ply(ply_file_path)
    bg_color = [0, 0, 0]
    bg_color = torch.tensor(bg_color, dtype=torch.float32, device="cuda")
    scaling_modifier = 1.0
    means3D = pc.get_xyz
    opacity = pc.get_opacity
    scales = pc.get_scaling * scaling_modifier
    rotations = pc.get_rotation
    colors = pc.get_features # [N, K, 3]
    sh_degree = pc.active_sh_degree
    
    print("Loading colmap data...")
    camera_params = dummyReadColmapSceneInfo(colmap_path)
    
    
    for frame in camera_params[0]:
        print(f"Processing frame: {frame.name}")

        #########
        # test rasterization
        ########
        viewmat = frame.world_view_transform.transpose(0, 1) # [4, 4]
        
        tanfovx = math.tan(frame.FoVx * 0.5)
        tanfovy = math.tan(frame.FoVy * 0.5)
        focal_length_x = frame.image_width / (2 * tanfovx)
        focal_length_y = frame.image_height / (2 * tanfovy)
        K = torch.tensor(
            [
                [focal_length_x, 0, frame.image_width / 2.0],
                [0, focal_length_y, frame.image_height / 2.0],
                [0, 0, 1],
            ],
            device="cuda",
        )

        render_colors, render_alphas, info = rasterization(
                                                                means=means3D,  # [N, 3]
                                                                quats=rotations,  # [N, 4]
                                                                scales=scales,  # [N, 3]
                                                                opacities=opacity.squeeze(-1),  # [N,]
                                                                colors=colors,
                                                                viewmats=viewmat[None],  # [1, 4, 4]
                                                                Ks=K[None],  # [1, 3, 3]
                                                                backgrounds=bg_color[None],
                                                                width=int(frame.image_width),
                                                                height=int(frame.image_height),
                                                                packed=False,
                                                                sh_degree=sh_degree,
                                                                # render_mode = "RGB+D",
                                                                rasterize_mode = "antialiased",
                                                                absgrad = True,       
                                                            )
        
        rendered_image = render_colors[0].permute(2, 0, 1)
        image_array = (rendered_image.detach().cpu().permute(1, 2, 0).numpy() * 255).astype('uint8')
        image_pil = Image.fromarray(image_array)
        image_pil.show()
        # image_pil.save("/HPS/ColorNeRF/work/gaussian-splatting-gsplat/output_test_5.png")
        
        #########
        # test _rasterize_to_pixels 
        ########
        Ks = K[None]
        viewmats = viewmat[None]
        height = int(frame.image_width)
        width = int(frame.image_height)
        quats = rotations
        scales = scales * 0.1
        means = means3D
        opacities = opacity.squeeze(-1)
        backgrounds=bg_color[None]
        C = len(Ks)

        covars, _ = quat_scale_to_covar_preci(quats, scales, compute_preci=False, triu=True)

        # Project Gaussians to 2D
        radii, means2d, depths, conics, compensations = fully_fused_projection(
            means, covars, None, None, viewmats, Ks, width, height
        )
        opacities = opacities.repeat(C, 1)

        # Identify intersecting tiles
        tile_size = 16 #if channels <= 32 else 4
        tile_width = math.ceil(width / float(tile_size))
        tile_height = math.ceil(height / float(tile_size))

        tiles_per_gauss, isect_ids, flatten_ids = isect_tiles(
            means2d, radii, depths, tile_size, tile_width, tile_height
        )

        isect_offsets = isect_offset_encode(isect_ids, C, tile_width, tile_height)

        _render_colors, _render_alphas = _rasterize_to_pixels(
        means2d,
        conics,
        colors,
        opacities,
        width,
        height,
        tile_size,
        isect_offsets,
        flatten_ids,
        backgrounds=backgrounds,
        )

        rendered_image = _render_colors[0].permute(2, 0, 1)
        image_array = (rendered_image.detach().cpu().permute(1, 2, 0).numpy() * 255).astype('uint8')
        image_pil = Image.fromarray(image_array)
        image_pil.show()

        break

```

**Comment by pknmax** [comment]
![output_test_6](https://github.com/user-attachments/assets/7c52e165-648c-4249-9197-e7ad64a81506)
hi @liruilong940607 getting this kind of rendering, can you please tell why?

**Comment by liruilong940607** [comment]
what is your `sh_degree`? If it is not None you would need this line:

https://github.com/nerfstudio-project/gsplat/blob/56f186749edf500fbd023b4b73cd82beef17de3a/gsplat/rendering.py#L532-L533

Btw, one tip I can give for debugging is that you could run
```
from gsplat.rendering import rasterization, _rasterization

render_colors, render_alphas, info = rasterization(
                                                                means=means3D,  # [N, 3]
                                                                quats=rotations,  # [N, 4]
                                                                scales=scales,  # [N, 3]
                                                                opacities=opacity.squeeze(-1),  # [N,]
                                                                colors=colors, # [N, K, 3]
                                                                viewmats=viewmat[None],  # [1, 4, 4]
                                                                Ks=K[None],  # [1, 3, 3]
                                                                backgrounds=bg_color[None],
                                                                width=int(frame.image_width),
                                                                height=int(frame.image_height),
                                                                packed=False,
                                                                sh_degree=sh_degree,
                                                                # render_mode = "RGB+D",
                                                                # rasterize_mode = "antialiased",
                                                                # absgrad = True,       
                                                                )
 _render_colors, _render_alphas, _info = _rasterization(
                                                                means=means3D,  # [N, 3]
                                                                quats=rotations,  # [N, 4]
                                                                scales=scales,  # [N, 3]
                                                                opacities=opacity.squeeze(-1),  # [N,]
                                                                colors=colors, # [N, K, 3]
                                                                viewmats=viewmat[None],  # [1, 4, 4]
                                                                Ks=K[None],  # [1, 3, 3]
                                                                backgrounds=bg_color[None],
                                                                width=int(frame.image_width),
                                                                height=int(frame.image_height),
                                                                packed=False,
                                                                sh_degree=sh_degree,
                                                                # render_mode = "RGB+D",
                                                                # rasterize_mode = "antialiased",
                                                                # absgrad = True,       
                                                                )                                                          
```
These two should produce the same image. Then you can open up the `_rasterization` function like you are doing now and see where went wrong.

**Comment by pknmax** [comment]
hello @liruilong940607,
thanks for the help.

Suppose, if i want to just track and rasterize two pixel locations `[(659, 776.), (718, 778)]` from first rasterized frame w.r.t. first cam pose,
how do I pass/use these locations/ids in `accumulate()` to rasterize only those tracked locations for different cam poses?

**Comment by liruilong940607** [comment]
If you are looking for reading out an optical flow, you don't need to open up the rasterization function. You could reproject the pixel to 3D using the rendered depth map, and then project it to another image plane to get the corresponded pixel location in the other frame.

Here is a relevant issue: https://github.com/nerfstudio-project/gsplat/issues/203

Is that what you need?

**Comment by pknmax** [comment]
Hello @liruilong940607,

I tried the approach you suggested but the tracking is not good enough when camera moves a lot.
I have sent you some images to look at. 
Is there anything I can do to improve the results?
I would really appreciate your help.

Thank you very much.

**Comment by liruilong940607** [comment]
If the depth is not accurate, (which it can be because Gaussian splatting only optimize for rendered colors, not the geometry), then there is nothing we can do to get an accurate flow map from that.

**Comment by pknmax** [comment]
hi @liruilong940607, can you please check the images of sample depth maps I sent to you via email? And tell me whether it is problem with depth map or something else?
