### ISSUE TITLE
Typo documentation utils spherical_harmonics

### ISSUE THREAD

**Issue by ghost** [nerfstudio-project/gsplat#114]
Looking at the documentation, the `spherical_harmonics` method returns dtype `Float[Tensor, ‘*batch D C’]`, but using this method I found it actually returns a `*batch C` shaped tensor. Am I using this method wrong or is the returntype supposed to be `*batch C`?
Code to test:

```py
import torch,gsplat

N = 100
sh_degree = 3
D = (sh_degree+1)**2 # =16
C = 3

viewdirs = torch.rand(N,3)
viewdirs /= torch.linalg.norm(viewdirs,dim=1,keepdim=True)

coefs = torch.rand(N,D,C)

out = gsplat.spherical_harmonics(sh_degree, viewdirs, coefs)

print("Output shape:")
print(out.shape) # Outputs 100,3. Expected 100,16,3
```

**Comment by maturk** [comment]
Hi @12626538, you are correct this is a mistake by me. Thanks for pointing it out.  Fix here #116
