### ISSUE TITLE
what is the range of rgbs

### ISSUE THREAD

**Issue by littlepure2333** [nerfstudio-project/gsplat#121]
Hi thanks for your amazing work. But I am wondering what is the range of rgbs. Is it (0,1)?

**Comment by maturk** [comment]
@littlepure2333 yep

**Comment by littlepure2333** [comment]
Btw, what is the range of depths?

**Comment by maturk** [comment]
@littlepure2333, the depths from project_gaussians can be 0 to inf from my understanding. The depths are directly the z-coordinate of the points in camera space.

**Comment by RupertPaoZ** [comment]
> @littlepure2333 yep

hello, I wonder to know what will happen if I use rgb in (0,inf).  It will just clip it into (0, 1) or cause something uncertain?
The gsplat version I use is v1.1.1

**Comment by maturk** [comment]
> > @littlepure2333 yep
> 
> hello, I wonder to know what will happen if I use rgb in (0,inf). It will just clip it into (0, 1) or cause something uncertain? The gsplat version I use is v1.1.1

Hi @RupertPaoZ, with the most recent version of gsplat, you can input any values to rasterize (so (o,inf)) is fine. You just have to make sure you deal with any clipping like `rgb = torch.clamp(rgb, 0.0, 1.0)` yourself.
