### ISSUE TITLE
Why there are two identical viewmat as inputs of “project_gaussians”？

### ISSUE THREAD

**Issue by littlepure2333** [nerfstudio-project/gsplat#137]
Hi thanks for you wonderful work. I have a little question: in the example simple trainer, these two inputs of function "project_gaussians" should be view matrix and projection matrix according to mathematical supplement, but why they are both view matrix?

https://github.com/nerfstudio-project/gsplat/blob/24215cb23e2bb5bdcfc9cdf67b98ce8e49a718b1/examples/simple_trainer.py#L106-L107

**Comment by vye16** [comment]
hello, apologies for this confusion. this should be the composed proj_mat @ view_mat, but out of laziness, we've just used the viewmat. this second argument will be deprecated in #97
