### ISSUE TITLE
spherical harmonics shift by 0.5?

### ISSUE THREAD

**Issue by Linusnie** [nerfstudio-project/gsplat#147]
Hi, amazing work with this implementation! Really great to have all the rendering components separately

I'm looking into using `gsplat` to render the output of the original gaussian splatting pipeline. 

In the process I've found that I need to add 0.5 to the output of `gsplat.spherical_harmonics` to get the correct colors:
```python
harmonics = gsplat.spherical_harmonics(
    degrees_to_use=max_sh_degree,
    viewdirs=view_dirs,
    coeffs=torch.tensor(features).to("cuda")
)
colors = harmonics + .5
```
where `features` are loaded directly from the `.ply` file generated by gaussian-splatting (original implementation). I was only able to figure this out by comparing implementations and spotting the 0.5 shift [here](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/cuda_rasterizer/forward.cu#L63) in diff-gaussian-rasterization.

Is this just due to a difference in conventions? If so it would be nice if it was documented somewhere.

![Screenshot from 2024-03-20 17-59-08](https://github.com/nerfstudio-project/gsplat/assets/12471058/321e18ca-bcc4-486d-a353-10e9683a6964)![Screenshot from 2024-03-20 17-59-42](https://github.com/nerfstudio-project/gsplat/assets/12471058/eab2efc8-61cf-474e-9d44-c76a75af6853)

Full example code here: https://github.com/Linusnie/render-splats/blob/main/splats.ipynb

**Comment by jb-ye** [comment]
Your observation is correct. if features are all zero, the color is 0.5. 

See https://github.com/nerfstudio-project/nerfstudio/blob/main/nerfstudio/models/splatfacto.py#L745
