### ISSUE TITLE
 Run on Mip-Nerf 360/ Comap dataset

### ISSUE THREAD

**Issue by wdkkkk** [nerfstudio-project/gsplat#174]
Hello, Are there any demos that can directly run on the Mip-Nerf 360/Comap dataset? 
Thanks!

**Comment by maturk** [comment]
Hi @wdkkkk , this repo implements the backend of 3DGS, not the actual training code (higher level python stuff). If you want to train on some colmap dataset, you can use the [splatfacto](https://docs.nerf.studio/nerfology/methods/splat.html) model from Nerfstudio which implements all the data-processing, loading, and training logic on top of the gsplat repo.
