### ISSUE TITLE
version number format for v0.1.12

### ISSUE THREAD

**Issue by desmondlzy** [nerfstudio-project/gsplat#196]
hey just noticed a very tiny discrepancy (not even a bug in the code). the tag name of the recent release v0.1.12 (commit 2d45698) seems to be tagged as "v.0.1.12" where there seems to be an extra dot between "v" and "0.1.12", screenshot below

also wanted to say -- thanks a ton for all the efforts you put into developing this amazing project

<img width="375" alt="Screenshot 2024-06-03 at 17 01 19" src="https://github.com/nerfstudio-project/gsplat/assets/38628974/fd1650e6-c0b9-4198-95ed-b482f9764b56">

**Comment by ichsan2895** [comment]
Yeah, I also aware for that typo. Hopefully it won't cause any bug, since `pip install gsplat==0.1.12` works well

**Comment by liruilong940607** [comment]
Yeah just fixed on github release. pypi is unaffected.
