### ISSUE TITLE
Is there a quick way of leveraging this codebase for CPU instead of GPU?

### ISSUE THREAD

**Issue by ChaosAdmStudent** [nerfstudio-project/gsplat#205]
I know this is a CUDA-accelerated library, but I am just wondering if I can easily migrate the code functionalities like fitting on images to the CPU implementation? 

It would be really helpful for my use-case. Thanks!

**Comment by liruilong940607** [comment]
Not really -- you would need to implement a few CPU kernels to make it work on CPU

**Comment by ivanpuhachov** [comment]
I believe you can use code from `_torch_impl.py` (https://github.com/nerfstudio-project/gsplat/blob/main/gsplat/cuda/_torch_impl.py) at the cost of compute time

**Comment by liruilong940607** [comment]
> I believe you can use code from `_torch_impl.py` (https://github.com/nerfstudio-project/gsplat/blob/main/gsplat/cuda/_torch_impl.py) at the cost of compute time

Yes most of the functions have its pure torch version with only two warnings that I would like to point out:

- `_rasterize_to_pixels()` still relies on CUDA: It relies on `rasterize_to_indices_in_range()` which is compiled from a customized cuda kernel, and it also relies on [nerfacc](https://github.com/nerfstudio-project/nerfacc) which only works with CUDA.

- the pure torch implementation of `_isect_tiles()` is via a forloop so could be extremely slow when using it in an actual rendering process.

Other than that the functions in `_torch_impl.py` should be fairly good (implemented in a proper batch way). They would certainly run slower tho but should be acceptable.

**Comment by ChaosAdmStudent** [comment]
Thanks a lot!
