### ISSUE TITLE
ImportError: cannot import name 'SceneManager' from 'pycolmap'

### ISSUE THREAD

**Issue by softyoda** [nerfstudio-project/gsplat#207]
Hi I have the following error when I try to execute simple_trainer.py

```
(base) C:\Users\intel>python "C:\Users\intel\Documents\05_3DGS\gsplat\examples\simple_trainer.py" --data_dir C:\Users\intel\Desktop\test_3dgs --data_factor 4 --result_dir "C:\Users\intel\Desktop\test_3dgs\output"
Traceback (most recent call last):
  File "C:\Users\intel\Documents\05_3DGS\gsplat\examples\simple_trainer.py", line 16, in <module>
    from datasets.colmap import Dataset, Parser
  File "C:\Users\intel\Documents\05_3DGS\gsplat\examples\datasets\colmap.py", line 8, in <module>
    from pycolmap import SceneManager
ImportError: cannot import name 'SceneManager' from 'pycolmap' (C:\Users\intel\AppData\Roaming\Python\Python311\site-packages\pycolmap.cp311-win_amd64.pyd)
```

**Comment by liruilong940607** [comment]
Did you run `pip install -r examples/requirements.txt`? More specifically it needs to install `git+https://github.com/rmbrualla/pycolmap@cc7ea4b7301720ac29287dbe450952511b32125e`

**Comment by softyoda** [comment]
I am sorry, i didn't found this [readme ](https://github.com/nerfstudio-project/gsplat/blob/main/docs/INSTALL_WIN.md)for windows user, I'll close this issue as it isn't really relevant to official documentation, i think I just had tried 
``pip install gsplat``
and
``pip install git+https://github.com/nerfstudio-project/gsplat.git`` 
but it is only for linux users.

Maybe the [website](https://docs.gsplat.studio/main/index.html) should have more link to this github as it may take some time for users to found official guide, current github link look more like star-count and the rest of the website look like self sustainable documentation without requiring to read github readme.
