### ISSUE TITLE
where to get `data/360_v2/garden`?

### ISSUE THREAD

**Issue by forresti** [nerfstudio-project/gsplat#223]
On this page https://docs.gsplat.studio/main/examples/large_scale.html

the instruction says to use `--data_dir data/360_v2/garden/`. What's the best place to get this data?

**Comment by maturk** [comment]
Hi, @forresti. You should be able to download the scenes from [here](https://jonbarron.info/mipnerf360/).

**Comment by forresti** [comment]
Thank you!
