### ISSUE TITLE
tips for beginner please.

### ISSUE THREAD

**Issue by RickMaruyama** [nerfstudio-project/gsplat#224]
Hello. 
I have a movie of a static object that I want to make it 3D ply of GS. 
my camera - monocular camera without depth info.
Can I do it with your gsplat?

What else data I need for that? for example, camera calibration data (camera parameter) is needed?

and then, can you shortly advise me the process? I've just finished install gsplat package on ubuntu.

Thank you for your response in advance!

**Comment by maturk** [comment]
@RickMaruyama, you can consider checking out the [nerfstudio](https://docs.nerf.studio/index.html) project and documentation. Within it, you can easily process your data (camera calibration) and run and train a gaussian splatting model (which uses gsplat) using the splatfacto model. This is quite a user-friendly introduction to get you started with splatting and has all the tools you need.

**Comment by RickMaruyama** [comment]
Thank you for quick response. I understand the function of gsplat is same as inria- GS, right? and how's difference with/without camera calibration parameter? in my understanding, it's fine without camera parameter.

Thank you for your short notice.

**Comment by maturk** [comment]
@RickMaruyama , to train a gaussian splatting scene, you need to estimate the poses of your cameras as well as their intrinsics (if you do not know them a priori). This requirement is true for GS/ NeRF based methods (inria-gs as well). gsplat is equivalent to inria-gs; however, gsplat has some additional features that you can read about in the documentation (depth rendering, pose optimization, batch rendering, anti-aliasing ... a few nice python bindings etc etc). You can refer to the documentation in nerfstudio or gsplat for more details.

**Comment by maturk** [comment]
If you have a colmap processed dataset, you can also use the `examples/simple_trainer.py` script to train your GS.
