### ISSUE TITLE
Is there any plan on integrating GaussianPro here? 

### ISSUE THREAD

**Issue by rkakash59** [nerfstudio-project/gsplat#230]
GaussianPro (https://github.com/kcheng1021/GaussianPro) gives better results when compared to 3DGS.

it would be good do choose different Gaussian splatting models for training with permissive license.

**Comment by maturk** [comment]
It's not planned. gsplat is mainly for the cuda backend, not higher level features which are implemented within the python training logic. Note that gaussian pro uses the default inria based [diff-gaussian-rasterization](https://github.com/graphdeco-inria/diff-gaussian-rasterization/tree/59f5f77e3ddbac3ed9db93ec2cfe99ed6c5d121d) backend, which can in theory be completely replaced with the gsplat API interface.
