### ISSUE TITLE
Is integrating dynamic Gaussian splatting here planned?

### ISSUE THREAD

**Issue by rkakash59** [nerfstudio-project/gsplat#233]
Also it would be great if we can have pose free Gaussian splatting here.(for both static and dynamic scenes)

**Comment by liruilong940607** [comment]
Unfortunately that is out of scope of this repo, which is focusing an efficient implementation of the GS rasterization process using CUDA. We provide an example code only for the purpose of demonstration on how to use `gsplat` for 3DGS training.
