### ISSUE TITLE
Prefilter the invisible 3DGS before splatting on images.

### ISSUE THREAD

**Issue by Miaosheng1** [nerfstudio-project/gsplat#236]
For large-scale scenes, particularly in the forward-moving street scenes, some 3D Gaussians may lie outside the current camera frustum. A better way to save memory and accelerate the speed is to filter some 3DGS that are not visible within the camera's view frustum before execute `rasterization`. Have you implemented this component?

**Comment by liruilong940607** [comment]
Hi,

The camera frustum filtering logic you described is implemented in the projection function at [here](https://github.com/nerfstudio-project/gsplat/blob/3b38568e43c48b83601d9344aa16de2008e5056a/gsplat/cuda/csrc/projection.cu#L606-L716), which is the first step in the `rasterization()` function:

https://github.com/nerfstudio-project/gsplat/blob/3b38568e43c48b83601d9344aa16de2008e5056a/gsplat/rendering.py#L211-L228
