### ISSUE TITLE
Error when loading MipNerf360 using pycolmap

### ISSUE THREAD

**Issue by holmes969** [nerfstudio-project/gsplat#237]
I followed the installation instruction and managed to set up the codebase on my Windows machine under conda environment. However, when I tried to run the `simple_trainer.py` with the command suggested by the [documents](https://docs.gsplat.studio/main/examples/colmap.html), I got error
```
File "C:\Users\holmes969\AppData\Local\anaconda3\envs\gsplat\Lib\site-packages\pycolmap\scene_manager.py", line 101, in _load_cameras_bin
    num_cameras = struct.unpack('L', f.read(8))[0]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
struct.error: unpack requires a buffer of 4 bytes
```
which seems to be a dumb bug in pycolmap when loading colmap data from [MipNerf360](https://jonbarron.info/mipnerf360/).

**Comment by liruilong940607** [comment]
Ah interestingly this won't be triggered on a linux system. 

I'm not very sure on how to fix this, but feels like it relates to that the `unsigned long integer` has different sizes (8 bits v.s. 4 bits) on different platforms?

Maybe try the following? (not 100% sure)

```
num_cameras = struct.unpack('I', f.read(4))[0]
```

**Comment by holmes969** [comment]
This platform seems to be more than only this line. I rewrote the colmap loader following the implementation [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/colmap_loader.py) and it seems to work fine at least under Windows.

**Comment by oo0o00oo0** [comment]
> This platform seems to be more than only this line. I rewrote the colmap loader following the implementation [here](https://github.com/graphdeco-inria/gaussian-splatting/blob/main/scene/colmap_loader.py) and it seems to work fine at least under Windows.

Would you be able to share this fix please?
