### ISSUE TITLE
`sh-degree = 0` causes bug on `gsplat=1.0.0`

### ISSUE THREAD

**Issue by kevin-thankyou-lin** [nerfstudio-project/gsplat#268]
Hi,

When I set `sh-degree = 0` (`ns-train splatfacto --pipeline.model.sh-degree 0 nerfstudio-data  --data <data>`) , I get this error:

```
  File "/scr/thankyou/autom/nerfstudio/nerfstudio/models/splatfacto.py", line 760, in get_outputs
    render, alpha, info = rasterization(
  File "/scr/thankyou/miniforge3/envs/acta/lib/python3.8/site-packages/gsplat/rendering.py", line 201, in rasterization
    assert (colors.dim() == 2 and colors.shape[0] == N) or (
AssertionError: torch.Size([811783, 1, 3])
```

I'm on `gsplat=1.0.0` and `nerfstudio==1.1.2`. Pre-gsplat=1.0.0 versions didn't cause an error when setting `sh-degree=0`. Would you know what the issue might be?

Thanks,
Kevin

**Comment by liruilong940607** [comment]
Should be fixed now on nerfstudio main branch! Feel free to reopen it if the problem still exists!

**Comment by kevin-thankyou-lin** [comment]
Thanks, Ruilong!
