### ISSUE TITLE
Is there any plan on integrating Rade-GS?

### ISSUE THREAD

**Issue by InFistLee** [nerfstudio-project/gsplat#271]
Hi, I wonder if there is a plan on integrating the depth calculation from Rade-GS ([https://baowenz.github.io/radegs/](url)) into the gsplat framework? It seems solid and is very relevant with the 3dgs-rasterizer.

Besides, many recent works that improve geometry quality of 3dgs (2dgs, GOF, Rade-GS) applies **depth-distortion loss** and **normal-consistent loss**. Computing these two losses both requires the assistant from rasterizer, so what about the plan on these two losses?

**Comment by liruilong940607** [comment]
You could check out these PRs #273 #244 for the moment. The depth formulation from Rade-GS is also on the way

**Comment by InFistLee** [comment]
@liruilong940607 appreciate that! Looking forward to the formal release.
