### ISSUE TITLE
Only Depth-Driven Training For Colorless Dataset

### ISSUE THREAD

**Issue by yunusstalha** [nerfstudio-project/gsplat#276]
Is it possible to train gsplat using your framework for only generating depthmaps without rgb  information ?

**Comment by Atticuszz** [comment]
wondering as well

**Comment by liruilong940607** [comment]
Yes very doable. Our `rasterization()` API support only render out the depth map ([API link](https://docs.gsplat.studio/main/apis/rasterization.html#gsplat.rasterization)):
> render_mode – The rendering mode. Supported modes are “RGB”, “D”, “ED”, “RGB+D”, and “RGB+ED”. “RGB” renders the colored image, “D” renders the accumulated depth, and “ED” renders the expected depth. Default is “RGB”.

That being said, it is very doable but you would need to modify the training script accordingly.

**Comment by huster-wugj** [comment]
> Yes very doable. Our `rasterization()` API support only render out the depth map ([API link](https://docs.gsplat.studio/main/apis/rasterization.html#gsplat.rasterization)):
> 
> > render_mode – The rendering mode. Supported modes are “RGB”, “D”, “ED”, “RGB+D”, and “RGB+ED”. “RGB” renders the colored image, “D” renders the accumulated depth, and “ED” renders the expected depth. Default is “RGB”.
> 
> That being said, it is very doable but you would need to modify the training script accordingly.

Is there any examples? I want to try train with depth and rgb data.

**Comment by Atticuszz** [comment]
> > Yes very doable. Our `rasterization()` API support only render out the depth map ([API link](https://docs.gsplat.studio/main/apis/rasterization.html#gsplat.rasterization)):
> > 
> > > render_mode – The rendering mode. Supported modes are “RGB”, “D”, “ED”, “RGB+D”, and “RGB+ED”. “RGB” renders the colored image, “D” renders the accumulated depth, and “ED” renders the expected depth. Default is “RGB”.
> > 
> > That being said, it is very doable but you would need to modify the training script accordingly.
> 
> Is there any examples? I want to try train with depth and rgb data.

https://github.com/nerfstudio-project/gsplat/tree/main/examples，here are examples

**Comment by yunusstalha** [comment]
one other question is how depth is handled or rasterized? For depth loss, what is the gt depth data ? Is it normalized-single channel image or metric depth ?

**Comment by Atticuszz** [comment]
> one other question is how depth is handled or rasterized? For depth loss, what is the gt depth data ? Is it normalized-single channel image or metric depth ? 

as for `how depth is handled or rasterized?`，you can scroll down  to the button  of README.md of gsplat.there is a arxiv paper of explanation of rasterization，for depths loss ,according to the normalization pipeline in calmap,gt depth is [produced](https://github.com/nerfstudio-project/gsplat/blob/main/examples%2Fdatasets%2Fcolmap.py#L168-L310) via unprojecting normed points and pose,and my dataset  is RGBD  image my strategy is rasterizing the normed points in camera coordinate,I think there's a quicker way in mathematics but have not deducted now

**Comment by RayYoh** [comment]
> > one other question is how depth is handled or rasterized? For depth loss, what is the gt depth data ? Is it normalized-single channel image or metric depth ?
> 
> as for `how depth is handled or rasterized?`，you can scroll down to the button of README.md of gsplat.there is a arxiv paper of explanation of rasterization，for depths loss ,according to the normalization pipeline in calmap,gt depth is [produced](https://github.com/nerfstudio-project/gsplat/blob/main/examples%2Fdatasets%2Fcolmap.py#L168-L310) via unprojecting normed points and pose,and my dataset is RGBD image my strategy is rasterizing the normed points in camera coordinate,I think there's a quicker way in mathematics but have not deducted now

Hi, I am also now using RGB-D datasets. I am wondering if I can directly use the GT depth map as the supervising signal.

**Comment by yunusstalha** [comment]
If I understand correctly, yes. There is a depth-map based loss which acts as regularizer. You might also check the literature, but as Atticus described you can find it in readme and example scripts.
