### ISSUE TITLE
No module named 'gsplat.relocation' when trying to run simple_trainer_mcmc.py

### ISSUE THREAD

**Issue by MasahiroOgawa** [nerfstudio-project/gsplat#279]
I got the 
> Traceback (most recent call last):
  File "/mnt/home/mas/proj/study/computer_vision/gsplat/examples/simple_trainer_mcmc.py", line 29, in <module>
    from gsplat.relocation import compute_relocation
ModuleNotFoundError: No module named 'gsplat.relocation'

error when I run 
```
python simple_trainer_mcmc.py
```

**Comment by MasahiroOgawa** [comment]
I can successfully run simple_trainer.py which has the line;
```
from gsplat.rendering import rasterization
```
So I checked difference between simple_trainer.py and simple_trainer_mcmc.py, and add below line into gsplat/__init__.py
```
from .relocation import (
    compute_relocation,
)
```
But it still fails with the same error.

**Comment by MasahiroOgawa** [comment]
I added gsplat to PYTHONPATH as below and it worked.
```
export PYTHONPATH="${PYTHONPATH}:/mnt/home/mas/proj/study/computer_vision/gsplat"
```

**Comment by MasahiroOgawa** [comment]
Thanks, I will try it.

**Comment by MasahiroOgawa** [comment]
@liruilong940607  I reinstall gsplat but the result is the same.
The newly installed version is still 1.0.0.
Is this correct?

**Comment by MasahiroOgawa** [comment]
Oh, I'm sorry, I didn't noticed the install command is
```
pip install .
```
I will try it.

**Comment by MasahiroOgawa** [comment]
I got other error by running 
```
pip install .
```
I will try to solve it.

# Error Detail
I'm using poetry environment named gsplat-pip, and I ran
```
poetry remove gsplat
poetry shell
pip install .
```
Then I got below error.
>     File "/tmp/pip-build-env-ikm6lmo4/overlay/lib/python3.11/site-packages/poetry/core/masonry/utils/module.py", line 65, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package gsplat-pip
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gsplat-pip
Failed to build gsplat-pip
ERROR: Could not build wheels for gsplat-pip, which is required to install pyproject.toml-based projects

**Comment by liruilong940607** [comment]
I'm not familiar with poetry. It seems like this error has something to do with that.

**Comment by Atticuszz** [comment]
in my case ，after poetry shell，just run with pip uninstall gsplat and then pip install . works for me on local installation，but the package name would not appear  in pyproject.toml,gpt told me try poetry  add . instead of pip
install. though  I haven't test it now

**Comment by MasahiroOgawa** [comment]
@Atticuszz Yes, I already tried 
```
poetry remove gsplat
poetry add gsplat
```
But the error "No module named 'gsplat.relocation'" occurred.
And yes, I did ```pip install .``` in gsplat/ directory instead of gsplat/example directory.

**Comment by MasahiroOgawa** [comment]
I ran
```
poetry shell
pip uninstall gsplat
pip install .
```
But the same error (ERROR: Failed building wheel for gsplat-pip) occurred.

**Comment by MasahiroOgawa** [comment]
Anyway, [this method](https://github.com/nerfstudio-project/gsplat/issues/279#issuecomment-2222134590) solved the original error, so I will take the strategy.

But after that, I ran
```
poetry run python simple_trainer_mcmc.py
```
It crashed.
I will launch another issue for this.
