### ISSUE TITLE
[FEATURE REQUEST] Any plans to enable training from Record3D captures? 

### ISSUE THREAD

**Issue by RR-28023** [nerfstudio-project/gsplat#283]
Hi! NeRF studio allows [training models from the export of Record3D](https://docs.nerf.studio/quickstart/custom_dataset.html#record3d) as an alternative to running COLMAP on RGB images. Any plans to work on that feature for gsplat? Not sure how hard that would be..

**Comment by liruilong940607** [comment]
Not at the moment. The script in this repo is just an **example code** to show case the features in this library. 

This library is in rapid development with the target users as the researchers in the field.

nerfstudio is more of a customer facing product so I'll refer you to use that repo instead, for the full import/export support.

**Comment by Ben-Mack** [comment]
@liruilong940607  I think it'd be best if this repo supports Nerfstudio format directly, then we can use ns-process-data to prepare dataset from various source. It will enable more dataset to test various algorithm/PR from this repo and giving more early feedback.
Do you think it'd be a feasible addition?
