### ISSUE TITLE
Technical report

### ISSUE THREAD

**Issue by hieu1999210** [nerfstudio-project/gsplat#293]
Hello,

Thank you for this awesome project.

Do you have any plans to write a technical report regarding the optimizations having been made to make this library more efficient than the official implementation?

Thanks.

**Comment by liruilong940607** [comment]
Hi the tech report is on the way. We are drafting it at the moment. If you would like to cite us please cite [this one ](https://arxiv.org/abs/2312.02121) for now. If for self learning purposes I guess nothing speaks more than the code itself :)

**Comment by hieu1999210** [comment]
Thanks
