### ISSUE TITLE
Scale and normalization of means2d grad

### ISSUE THREAD

**Issue by soskek** [nerfstudio-project/gsplat#298]
I have a question on implementation.
In `DefaultStrategy`, GS growth is done with a comparison of a threshold and a gradient norm.
The calculation of the gradient norm is finally done here:

https://github.com/nerfstudio-project/gsplat/blob/5fc940b648e32218ba0979355d7e4d7910f54476/gsplat/strategy/default.py#L201-L207

But, in my understanding, `info["means2d"].grad` (and `means2d` itself) is in pixel space.

ref. (cuda may be the same)
https://github.com/nerfstudio-project/gsplat/blob/5fc940b648e32218ba0979355d7e4d7910f54476/gsplat/cuda/_torch_impl.py#L100-L102

So, if we want to realize `# normalize grads to [-1, 1] screen space`, should we use `/=` like this?
```
 grads[..., 0] /= info["width"] / 2.0 * info["n_cameras"] 
 grads[..., 1] /= info["height"] / 2.0 * info["n_cameras"] 
```

**Comment by liruilong940607** [comment]
For the forward values yes you would use `/=` to normalize. But gradient is the backward values, which actually needs to be normalized with `*=`. This is a bit counterintuitive but if you work out the math you would see it

**Comment by soskek** [comment]
Oh, I got it. It sounds right. Thank you!
