### ISSUE TITLE
Tensor Size Mismatch after rasterization()

### ISSUE THREAD

**Issue by mizeller** [nerfstudio-project/gsplat#306]
I think my problem is related to this (resolved) issue #287 

After a few training iterations, the code breaks at the assertion (see below).
Somehow after `rasterization()` the #radii vs #gaussians is: 24593 vs. 24608 --> missing 15 gaussians?

```python
...
render_colors, render_alphas, info = rasterization(
        means=means3D,
        quats=rotations,
        scales=scales,
        opacities=opacity.squeeze(),
        colors=colors,
        viewmats=viewpoint_cam.world_view_transform.unsqueeze(0),
        Ks=viewpoint_cam.cam_intrinsics.unsqueeze(0),
        width=viewpoint_cam.image_width,
        height=viewpoint_cam.image_height,
        sh_degree=sh_degree,
        backgrounds=bg_color.unsqueeze(0),
        far_plane=100
    )

    radii = info["radii"].squeeze(0)  # [N,]
    assert radii.shape[0] == means3D.shape[0], "Radii shape mismatch after rasterization." 
```

Anyone w/ the same issue? I'd be very thankful for any possible solution!

**Comment by pknmax** [comment]
same here, with gsplat 1.1.1,

`gaussians.max_radii2D[visibility_filter] = torch.max(gaussians.max_radii2D[visibility_filter], radii[visibility_filter])`

---> `IndexError: The shape of the mask [30615] at index 0 does not match the shape of the indexed tensor [33437] at index 0`

have you resolved the issue?

**Comment by liruilong940607** [comment]
Hi,

The default `rasterization` function set `packed=True` in its argument list, which means the intermediate tensors in the `info` dictionary might not have the same size with the number of Gaussians. Instead, only the visible Gaussians are kept:

See here:

https://github.com/nerfstudio-project/gsplat/blob/19d8da517b09a3e087971fbad609a67fb51ad07c/gsplat/rendering.py#L68-L74

**Comment by pknmax** [comment]
hi @liruilong940607,
yes, with `packed=False`, shapes of `info `and number of `gaussians` becomes equal,
but then how we can handle the unequal shapes of `info `and number of `gaussians` when we use `packed=True`?

**Comment by mizeller** [comment]
Thanks a lot - this resolved the issue for me!
