### ISSUE TITLE
Typo in examples/simple_viewer

### ISSUE THREAD

**Issue by simo23** [nerfstudio-project/gsplat#316]
I believe there is an error in the simple_viewer example. In the ckpt "means3d" does not exist and should be "means". 

https://github.com/nerfstudio-project/gsplat/blob/7816033ef1ec0b1fe890cb251412efde19e37f36/examples/simple_viewer.py#L112

**Comment by liruilong940607** [comment]
Oh yes. would you like to PR it?

**Comment by simo23** [comment]
Created a [PR](https://github.com/nerfstudio-project/gsplat/pull/321).
