### ISSUE TITLE
Not working on Tanks&Temples scene

### ISSUE THREAD

**Issue by lukasHoel** [nerfstudio-project/gsplat#336]
Hi,

I try to adapt `examples/benchmarks/basic.sh` to run on the Tanks&Temples dataset, as published in the original 3DGS [here](https://repo-sam.inria.fr/fungraph/3d-gaussian-splatting/datasets/input/tandt_db.zip).

I run the following command

```
python simple_trainer.py default --eval_steps -1 --disable_viewer --data_factor 1 \
        --data_dir /path/to/tandt_db/tandt/train \
        --result_dir /path/to/results/train
```

but the optimization fails and only produces such images:

PSNR: 9.727, SSIM: 0.3667, LPIPS: 0.683 Time: 0.035s/image Number of GS: 192114

![val_0000](https://github.com/user-attachments/assets/c72187f0-ad92-4ee3-b9fe-3f4a1f6fbdd0)

Do I have to change any arguments in the `simple_trainer.py`?

**Comment by liruilong940607** [comment]
I don't think we ever run T&T dataset. This seems very strange as I think we aligned all configurations with the official repo. Would you mind posting your code as a PR so we can look into it?

**Comment by lukasHoel** [comment]
I did not modify the code in any way, I get this result when running the command mentioned above on the current state of the main branch.

**Comment by liruilong940607** [comment]
Hey @lukasHoel, sorry for the delay. I just looked into this issue, and find out if modify this line

https://github.com/nerfstudio-project/gsplat/blob/8e39e4157712f53082480c978a89760975f8e107/examples/datasets/colmap.py#L75

into 

```
fx, fy, cx, cy = cam.fx / 2, cam.fy / 2, cam.cx / 2, cam.cy / 2
```

The t&t data would train normally. 

I'm not sure why the original 3dgs repo can train this data without any issue, but I think the data (downloaded from 3dgs repo readme) should have some issue. For example, for the `train` capture, the image size is `980x545`, but the principle points (`cam.cx`, `cam.cy`) that we read out is `979.5 545.0`.

**Comment by liruilong940607** [comment]
I see. The original 3dgs repo represent the camera intrinsic with FoV instead of intrinsic matrix. So the `/2` cancelled out. That's why it works normally in their repo.

**Comment by lukasHoel** [comment]
Thank you, I can confirm that it now also works for me with this fix!
