### ISSUE TITLE
Resolution decreases during rendering

### ISSUE THREAD

**Issue by smart4654154** [nerfstudio-project/gsplat#343]
Resolution decreases during rendering
Thank you very much, I encountered a bug while using the CityGaussian viewer.
This viewer is based on VISER.  I set the resolution to 1920, the photo quality to 100, and the moving resolution to 1920, the photo quality to 100.
1.During my movement, there was a noticeable decrease in resolution. When I finished moving and stopped pressing the keyboard, the rendering result suddenly became clear. 
For example ,from 28 seconds to 31 seconds in the video. This phenomenon is abnormal, theoretically the resolution should remain unchanged when moving.
2.When I finish moving and no longer press the keyboard, the rendering result is unclear. 
For example ,within 1 minute and 38 seconds of the video and beyond. This phenomenon is abnormal, theoretically the resolution should remain unchanged after the movement is completed.
Note: At other times, the resolution remains unchanged after the movement ends.
I'm not sure if this is a bug in Viser or GSPlat, can you help me? thank you.

the vedio:https://www.youtube.com/watch?v=KvWrNXg3BeA

**Comment by liruilong940607** [comment]
Our viewer has a hidden logic that if you are moving camera and the rendering is slow, then we automatically switch to render lower res image to maintain a smooth camera movement. And when you stop moving your camera, the rendering boost the resolution to your desired resolution (1902 in your case).

**Comment by smart4654154** [comment]
> Our viewer has a hidden logic that if you are moving camera and the rendering is slow, then we automatically switch to render lower res image to maintain a smooth camera movement. And when you stop moving your camera, the rendering boost the resolution to your desired resolution (1902 in your case).

thank you 
Q1 How can I change a hidden logic? I want to always render clearly
Q2 when i stop moving your camera, the rendering does not  boost the resolution to your desired resolution
the example:
When I finish moving and no longer press the keyboard, the rendering result is unclear.
For example ,within 1 minute and 38 seconds of the video and beyond. This phenomenon is abnormal, theoretically the resolution should remain unchanged after the movement is completed.

**Comment by liruilong940607** [comment]
Q1. I'm not sure you would have to look into this repo: https://github.com/hangg7/nerfview

Q2. Are you sure the unsatisfied rendering quality is caused by the viewer, instead of the 3dgs model? Tbh I dont see any issue from your shared video at 1:38 on wards.

**Comment by smart4654154** [comment]
> Q1. I'm not sure you would have to look into this repo: https://github.com/hangg7/nerfview
> 
> Q2. Are you sure the unsatisfied rendering quality is caused by the viewer, instead of the 3dgs model? Tbh I dont see any issue from your shared video at 1:38 on wards.




Thank you very much for your patient reply
Q1: I know nerfview, function( _get_img_wh) seems to be the hidden logic

def _get_img_wh(self, aspect: float) -> Tuple[int, int]:
    max_img_res = self.viewer._max_img_res_slider.value
    if self._state == "high":#11
         # if True:
        H = max_img_res#
        W = int(H * aspect)#根据宽高比 aspect 计算宽度 W。
        if W > max_img_res:
            W = max_img_res#如果计算出的宽度 W 超过最大分辨率，则调整宽度为最大分辨率，并重新计算高度 H。
            H = int(W / aspect)
    elif self._state in ["low_move", "low_static"]:
         num_view_rays_per_sec = self.viewer.state.num_view_rays_per_sec
         target_fps = self._target_fps#30
         num_viewer_rays = num_view_rays_per_sec / target_fps#每次渲染的光线数量
         H = (num_viewer_rays / aspect) ** 0.5#计算理想的高度 H
         H = int(round(H, -1))#将高度 H 四舍五入到最近的 10 的倍数
         H = max(min(max_img_res, H), 30)#确保 H 在最小值 30 和最大分辨率 max_img_res 之间
         W = int(H * aspect)
         if W > max_img_res:
            W = max_img_res
             H = int(W / aspect)
    else:
        raise ValueError(f"Unknown state: {self._state}.")
    return W, H


in order to always render clearly,I change the _get_img_wh.During my movement, there was a noticeable decrease in resolution. 
def _get_img_wh(self, aspect: float) -> Tuple[int, int]:
max_img_res = self.viewer._max_img_res_slider.value
    if True:
        H = max_img_res#
        W = int(H * aspect)#根据宽高比 aspect 计算宽度 W。
        if W > max_img_res:
            W = max_img_res#如果计算出的宽度 W 超过最大分辨率，则调整宽度为最大分辨率，并重新计算高度 H。
            H = int(W / aspect)
    else:
        raise ValueError(f"Unknown state: {self._state}.")
    # print("WH不变",W,H)
return W, H

So I try another viewer based on viser( https://github.com/DekuLiuTesla/CityGaussian)
In this new viewer,I set the resolution to 1920, the photo quality to 100, and the moving resolution to 1920, the photo quality to 100.During my movement, there was a noticeable decrease in resolution.
CityGaussian developer said they meet similar performance(https://github.com/DekuLiuTesla/CityGaussian/issues/16#issuecomment-2301189111)
So I guess these phenomenons are mainly attributed to VISER itself.


Q2
You can see jagged edges in the red box. In theory, if I stop moving, the scene should become clearer, but the scene remains blurry.
 
![image](https://github.com/user-attachments/assets/c11a6e09-99df-4de0-b82a-de44d342aa00)


But in 14 seconds, the sea surface was very smooth

![image](https://github.com/user-attachments/assets/f943d99d-783e-48d0-b898-00be48424139)



Q3 By the way, do you know any simple solutions? https://github.com/nerfstudio-project/gsplat/issues/341 . Using nvCUDMP is difficult for beginners

**Comment by brentyi** [comment]
Mirroring my comment from https://github.com/nerfstudio-project/viser/issues/270:

Unfortunately I don't think there's anything that gsplat developers can do to help here, since the CityGaussian viewer doesn't use any viewer infrastructure provided by gsplat or nerfview. (it doesn't use gsplat at all)

If there's unexpected resolution behavior then the right place to look is probably here: https://github.com/DekuLiuTesla/CityGaussian/blob/main/viewer.py
