### ISSUE TITLE
CUDA runtime error with example script `bash benchmarks/basic.sh`

### ISSUE THREAD

**Issue by SirRacha** [nerfstudio-project/gsplat#344]
Nvidia pytorch docker 24.05
Ubuntu 22.04
GPU A6000

I am getting 2 errors trying to run the benchmarks/build.sh script
1. `Warning: image_path not found for reconstruction`
2. `RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.`

I have tried many things but cannot fix this error and thus cannot get the example evaluation or the simple_trainer.py to run.

I tried going with the gsplat installation that compiled gsplat during installation instead of JIT in my Dockerfile.  That did not work either.

**Comment by liruilong940607** [comment]
I'm not very sure but it feels like your docker image is probably not setup properly.

**Comment by SirRacha** [comment]
It was an issue with my Nvidia driver and not with Gsplat. This issue can be closed. Thank you for your comment and help!
