### ISSUE TITLE
gsplat Recompiles with torch.multiprocessing Process Everytime

### ISSUE THREAD

**Issue by xiemeilong** [nerfstudio-project/gsplat#345]
If I create multiple processes using `torch.multiprocessing` to run gsplat, gsplat recompiles itself every time. Even I install gsplat by run `pip install git+https://github.com/nerfstudio-project/gsplat.git`

**Comment by liruilong940607** [comment]
If you install via `pip install git+https://github.com/nerfstudio-project/gsplat.git`, it should trigger `setup.py`, which leads to a compile (into your env `site-packges/gsplat/csrc.so`) during the installation.  And in this case, `from gsplat import csrc` should work, which should avoid JIT recompiles, as coded here: 

https://github.com/nerfstudio-project/gsplat/blob/45d196a3611e627c498f237c27014cdaf42d94d2/gsplat/cuda/_backend.py#L81-L84

Could you try `from gsplat import csrc` in your multiprocessing program and see what it says?

**Comment by xiemeilong** [comment]
sorry , The problem disappeared after I rebuilt the venv.
