### ISSUE TITLE
ModuleNotFoundError: No module named 'gsplat.compression'

### ISSUE THREAD

**Issue by jujpenabe** [nerfstudio-project/gsplat#355]
Hi i'm trying to make the benchmark 
```
# run batch evaluation
bash benchmarks/basic.sh 
```
and I always get the following error with every example:

``Running garden
Traceback (most recent call last):
  File "/home/steamlinux/Documentos/Repositorios/gsplat/examples/simple_trainer.py", line 27, in <module>
    from gsplat.compression import PngCompression
ModuleNotFoundError: No module named 'gsplat.compression'``

I installed gsplat with both ways (just pip install gsplat and with the url).

What can I do in these case?
Thanks in advance

**Comment by liruilong940607** [comment]
Hey the compression part is not yet on pypi yet. You would need to install via:
```
pip install git+https://github.com/nerfstudio-project/gsplat
```

**Comment by liruilong940607** [comment]
We just bumped the version. Its now in gsplat==1.3.0
