### ISSUE TITLE
add the gsplat/compression folder to the published packages

### ISSUE THREAD

**Issue by martinResearch** [nerfstudio-project/gsplat#361]
for some reason the `gsplat/compression` folder does not appear in the published packages on pypi.org (source and wheel)

**Comment by liruilong940607** [comment]
yeah its not yet published. please install from source for now. We will publish it to pypi very soon after a few more tests

**Comment by martinResearch** [comment]
duplicate of https://github.com/nerfstudio-project/gsplat/issues/355
