### ISSUE TITLE
Is there a way to directly remove the huge splat? These splats are affecting almost my entire scene.

### ISSUE THREAD

**Issue by zhj296409022** [nerfstudio-project/gsplat#377]
Is there a way to directly remove the huge splat? These splats are affecting almost my entire scene. I don't want to use reset_every property because it causes the splat to move towards the camera, resulting in more floaters. refine_every property seems to be unable to remove the huge splat that is far away.

**Comment by liruilong940607** [comment]
have you tried the mcmc strategy? `python simple_trainer.py mcmc`
