### ISSUE TITLE
A bug in points projection when enabling patch_size?

### ISSUE THREAD

**Issue by nnop** [nerfstudio-project/gsplat#381]
Hi, thanks for the great work.

There may be a minor bug in generating points for depth loss when enabling patch_size.

The camera center is already changed in K.
https://github.com/nerfstudio-project/gsplat/blob/61be4a7443e17b4ff51aff6fc441e9d2ea2e95e4/examples/datasets/colmap.py#L281-L288

So, it seems the projected pixel coordinates by K needn't subtract x,y again.
https://github.com/nerfstudio-project/gsplat/blob/61be4a7443e17b4ff51aff6fc441e9d2ea2e95e4/examples/datasets/colmap.py#L307-L309

**Comment by liruilong940607** [comment]
I think you are right! Do you have any experiments that kinda verify this? Would be happy to accept a PR for it.

**Comment by nnop** [comment]
I test with garden data and patch size 800, plot the projected points and data['points']. 

It shows as follows. 
![image](https://github.com/user-attachments/assets/b197b40f-e898-4065-a548-2c7a523e78b1)
It can be seen the points are selected wrong and not consistent.

After fix the bug:
![image](https://github.com/user-attachments/assets/e935af0b-51a5-40fd-af2c-0d1dc6ef488c)
