### ISSUE TITLE
Viewing gsplat results in nerfstudio viewer, config? 

### ISSUE THREAD

**Issue by YuxinYao620** [nerfstudio-project/gsplat#395]
Hello. Thank you so much for this amazing work. 

I wonder how should I view the Gaussian splatting produced by the splat in the nerfstudio without an “config" file. I am not sure how to output a corresponding config file for my Gaussian splatting. 

I made some slight changes in the gsplat process so I wish to view the output checkpoint file including the Gaussian splatting argument instead of using the splatfacto in the nerfstudio.

Thank you very much!

**Comment by jckhng** [comment]
After running through some sample data, you should get a checkpoint file (.pt). Then you can pass it into simple_viewer.py using the following example:

`python simple_viewer.py --ckpt=results\benchmark\bonsai\ckpts\ckpt_6999_rank0.pt`

This will run the viser visualizer so you can view your results locally on your browser.

**Comment by jckhng** [comment]
I think simple_viewer.py is meant as a quick way to visualize the results from gsplat. It should be easier to work on nerfstudio, if you want to add custom camera path. simple_trainer.py has some camera path rendering functionality, but I have not used that before.

**Comment by kerrj** [comment]
You could try running splatfacto which is supported by the nerfstudio viewer!
