### ISSUE TITLE
CUDA error when training with fused-SSIM after 1000 iterations.

### ISSUE THREAD

**Issue by zhj296409022** [nerfstudio-project/gsplat#399]
loss=0.279| sh degree=1| depth loss=0.022742| :   3%|████▋                                                                                                                                    | 1022/30000 [01:24<40:07, 12.04it/s]
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/app/cache/gsplat/examples/simple_trainer.py", line 990, in <module>
    cli(main, cfg, verbose=True)
  File "/usr/local/lib/python3.10/dist-packages/gsplat/distributed.py", line 360, in cli
    return _distributed_worker(0, 1, fn=fn, args=args)
  File "/usr/local/lib/python3.10/dist-packages/gsplat/distributed.py", line 295, in _distributed_worker
    fn(local_rank, world_rank, world_size, args)
  File "/app/cache/gsplat/examples/simple_trainer.py", line 935, in main
    runner.train()
  File "/app/cache/gsplat/examples/simple_trainer.py", line 556, in train
    ssimloss = 1.0 - fused_ssim(
  File "/usr/local/lib/python3.10/dist-packages/fused_ssim/__init__.py", line 41, in fused_ssim
    return map.mean()
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by liruilong940607** [comment]
cc @rahul-goel

**Comment by rahul-goel** [comment]
Hi.

Looks like this is distributed training setting. I've not tested this in such a setting due the lack of proper access to multiple GPUs. @zhj296409022 Does this work fine with a single GPU in your environment? Can you let us know? This will help us confirm this suspicion.

@liruilong940607 It is probably best to turn of fused-ssim for multi-GPU for now if this is the case. I haven't looked at how multi-GPU in gsplat is working and I'm not confident about fused-ssim working in such a setting yet.

Rahul

**Comment by liruilong940607** [comment]
Ha right! I think you just need to guard the device in cuda kernels of fused-ssim (like what we do in gsplat), then it should be able to work nicely for the multi GPU case.

https://github.com/nerfstudio-project/gsplat/blob/2d6a967f92187daaa19f198613a7309e4d1a00dc/gsplat/cuda/csrc/fully_fused_projection_2dgs_bwd.cu#L170

I would be happy to PR it to fused-ssim and test it out over the weekend, if this hasn't been solved by then.

**Comment by zhj296409022** [comment]
sorry for the late reply. This is related to the CUDA device ID. I encountered an error when running with cuda:1, while cuda:0 works fine. I haven't checked the code; is it possible that it's not adapted?

**Comment by rahul-goel** [comment]
@liruilong940607 I'll wait for your PR to fused-ssim and then you can bump the commit it up here. I would do it myself but can't due to limited compute.

**Comment by rahul-goel** [comment]
Fused-SSIM has added the guard; thanks to @liruilong940607. Please feel free to bump up the version here.
