### ISSUE TITLE
2d_inria_wrapper using the wrong input for depth_to_normal

### ISSUE THREAD

**Issue by yifita** [nerfstudio-project/gsplat#406]
Shouldn't the input viewmat here be `cam_to_world` transformation?
The one used here is a `world_to_cam` matrix

https://github.com/nerfstudio-project/gsplat/blob/2d6a967f92187daaa19f198613a7309e4d1a00dc/gsplat/rendering.py#L1450C50-L1450C58

**Comment by liruilong940607** [comment]
Ah i think you are correct! Something we forgot to update during cleanup!
