### ISSUE TITLE
Equation 7 in the paper --> Camera intrinsics $ K $

### ISSUE THREAD

**Issue by Crescent-Saturn** [nerfstudio-project/gsplat#435]
Hi, I find out that there seems to be a typo in your [paper](https://arxiv.org/abs/2409.06765):
at Page 10, Section C.1, Equation 7, where the camera intrinsics $K$ is given as:

![image](https://github.com/user-attachments/assets/7cc32c54-f18b-4ce1-9a5c-ddc14996c1a9)

Should it be:

$$
K = 
\begin{bmatrix}
fx & 0 & cx \\
0 & fy & cy \\
0 & 0 & 1
\end{bmatrix}
$$

I have checked again, and there is only one version in arxiv site: https://arxiv.org/abs/2409.06765
> Submission history
From: Matias Turkulainen [[view email](https://arxiv.org/show-email/79a84e2c/2409.06765)]
[v1] Tue, 10 Sep 2024 17:57:38 UTC (208 KB)

**Comment by maturk** [comment]
Yeah I noticed this shortly after uploading... thanks for bringing it up. You are correct, the namings should be fx at index (0,0) and cy at index (2,1).
