### ISSUE TITLE
Spherical camera support for Gaussian splatting

### ISSUE THREAD

**Issue by inuex35** [nerfstudio-project/gsplat#439]
Hello, I have developed a 360-degree spherical camera implementation for Gaussian splatting and would like to submit a pull request to this repository. This was originally developed as a personal project, so implementing everything from the latest code by myself is challenging due to time constraints. Could you provide guidance on which parts of the source code would need modification to integrate this feature? I'd appreciate any suggestions on where to start.

https://github.com/inuex35/360-gaussian-splatting
https://github.com/inuex35/360-diff-gaussian-rasterization/tree/omnigs

Thank you for your help!

**Comment by maturk** [comment]
@inuex35, do you have a contact/email I can DM you, feel free to DM me as well if you want. I would be interested to learn what you have done in more detail. From what I understand in your repos you implemented panorama rendering by stitching multiple images and you also implemented spherical rendering?

**Comment by inuex35** [comment]
Currnt implementation is based on this paper. This can render spherical image directly.（This is not my paper though）
https://arxiv.org/abs/2404.03202
Where could I contact to you?

**Comment by maturk** [comment]
Yeah let me know how it goes, I would be interested in reviewing / helping you out if needed. matiasturkulainen@gmail.com

**Comment by reynoldscem** [comment]
What’s the current status of this?

**Comment by maturk** [comment]
@reynoldscem, spherical rendering and training works, please check repo here: https://github.com/inuex35/gsplat/tree/spherical_render. 

I am not entirely sure how to properly validate that the implementation is correct however, since there is no other reference implementation AFAIK.

**Comment by inuex35** [comment]
Closing here because I opened PR.
