### ISSUE TITLE
gsplat rasterization  gradient through pose

### ISSUE THREAD

**Issue by Gynjn** [nerfstudio-project/gsplat#440]
First, Thanks for sharing your great work.

I have a question about gradient through pose.

In simple trainer, pose optimization is used to get gradient from rasterization and updated by offset.

But if I get pose from, for example, pose encoder model and do rasterization, it still flow the gradient from rasterization to pose encoder in training?

Thanks in advance.

**Comment by maturk** [comment]
Yes, as long as your pose-encoder is differentiable as well.
