### ISSUE TITLE
Windows 11, python 3.10, cuda toolkit 11.8

### ISSUE THREAD

**Issue by 3a1b2c3** [nerfstudio-project/gsplat#48]
hi,
Thanks for all this. windows is silly again. When compiling from nerfstudio I get this error (running from nerfstudio) 

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin\nvcc --generate-dependencies-with-compile --dependency-output bindings.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4068 -Xcompiler /wd4067 -Xcompiler /wd4624 -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=gsplat_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\gsplat\cuda\csrc\third_party\glm -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\include -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\include\TH -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\include" -IC:\Users\kabis\AppData\Local\Programs\Python\Python310\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -std=c++17 -O3 -c C:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\gsplat\cuda\csrc\bindings.cu -o bindings.cuda.o        
C:\Users\kabis\AppData\Local\Programs\Python\Python310\lib\site-packages\gsplat\cuda\csrc\sh.cuh(6): error: attribute "__host__" does not apply here

**Comment by 3a1b2c3** [comment]
with pip install -e i gee this known https://github.com/facebookresearch/pytorch3d/issues/1227

**Comment by 3a1b2c3** [comment]
Cuda 12.1 works for me, run simple trainer

**Comment by liruilong940607** [comment]
I think this bug `sh.cuh(6): error: attribute "host" does not apply here` is fixed in https://github.com/nerfstudio-project/gsplat/commit/ee9f1b6a19a654529b05813d60d4c33fc189e383

**Comment by liruilong940607** [comment]
Close for now. Feel free to reopen if it is still a bug with the latest version.
