### ISSUE TITLE
Adapting 3D Gaussian Splatting to Different Camera Models

### ISSUE THREAD

**Issue by HarryPeverell** [nerfstudio-project/gsplat#490]
Hi,

First, I would like to express my gratitude for the excellent work you have done on this project. It’s been incredibly useful!

I have a question regarding the current implementation of 3D Gaussian splatting, which is based on a pinhole camera model. I am wondering if it would be possible to adapt the method to other camera models, such as orthographic or fisheye cameras. If so, what changes would need to be made to the existing code to accommodate these camera models?

I would greatly appreciate any guidance or suggestions you may have!

Thank you again for your great work.

Best regards,  
Harry

**Comment by jefequien** [comment]
These camera models are already implemented.
- Ortho: https://github.com/nerfstudio-project/gsplat/pull/349
- Fisheye: https://github.com/nerfstudio-project/gsplat/pull/398

**Comment by HarryPeverell** [comment]
Thanks a lot !
