### ISSUE TITLE
General Issue with windows .

### ISSUE THREAD

**Issue by FreeFlowVFX** [nerfstudio-project/gsplat#495]
Nothing works on windows 11 . Tried everything in last couple of days really everything ! We need real world installation guide for windows.  nerfstudio and gsplat don't seem to work on windows currently ! 
If one thing is fixed another is broken and is constant nightmare to install . 
I have VS 2002 installed with all of the requirements . I tried with conda  env and without . I am using  python 3.10 , I tried many different ways with system variables and so on . Specifically for gsplat kind of got it to somewhere  but when I try to install the requirements it breaks:

`     File "C:\Program Files\Python310\lib\site-packages\packaging\version.py", line 196, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for fused_ssim
  Running setup.py clean for fused_ssim
Successfully built pycolmap
Failed to build fused_ssim
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (fused_ssim)`

and let's say I fix  this something else will be broken. 
I have  torch  and cuda toolkit 11.8 , latest drivers,  I have everything as in the guide suggests  but nothing works . Never ever had such a pain to make something work!

**Comment by BaeLuv** [comment]
Did you solve this problem? I met same issue

**Comment by siryang** [comment]
gsplat/examples/simple_trainer.py", line 28, in <module>
    from fused_ssim import fused_ssim
ModuleNotFoundError: No module named 'fused_ssim'

**Comment by halil-karabacak** [comment]
> ```
> gsplat/examples/simple_trainer.py", line 28, in <module>
>     from fused_ssim import fused_ssim
> ModuleNotFoundError: No module named 'fused_ssim'
> ```

Use https://github.com/rahul-goel/fused-ssim. directly install using pip, it would work.
