### ISSUE TITLE
Unable to use my own point cloud and camera pose.

### ISSUE THREAD

**Issue by engs2570** [nerfstudio-project/gsplat#520]
Unable to use my own point cloud and camera pose.
I am trying to splatfacto. However, I do not want to use colmap. I have my own camera parameters and point cloud for each image. These are ground truth parameters. The colmap prediction is obviously not as good as ground truth. Consequently the reconstruction is not satisfactory. This I want to understand how to use my own parameters to train splat-facto.

**Comment by maturk** [comment]
Create a transforms.json file following the instructions from nerfstudio repo [here](https://docs.nerf.studio/quickstart/data_conventions.html#dataset-format). When you have a transforms.json file, you can use splatfacto with the ground truth poses. Remember to also fill in the 'pcd_path.ply" in the transforms.

**Comment by engs2570** [comment]
Any suggestions on what should be the size of the point cloud, how should i sparsify my dense point cloud or if point cloud is at all necessary? The script seems to be hanging with my dense pointcloud.

**Comment by maturk** [comment]
@engs2570, could you say how many points are in your dense pcd? From personal experience, SfM sparse point clouds are anywhere from 5-60k points in total, completely depending on the size of your scene and image number. 

You can always compress your pcd. Load it using some convenient tool like Open3D and randomly sample n points from it to make it sparser.

**Comment by engs2570** [comment]
I understand the reason why. My pcd has 115520000 points. I need to sparsify it. My GPU is NVIDIA RTX A5000 24 GB and I have 32 GB RAM. So i need to sparsify. Do I need the pointcloud though? the system seems to continue training without point cloud.

**Comment by maturk** [comment]
You can also initialize with random points. But you get best results with a good sparse initialization.

**Comment by engs2570** [comment]
Thank you. I have tried all sorts of options but my results are really poor. Both when I use my own pose or when I use the colmap. 
With my data I just gate grey points, but the shape is correct so I assume the way I inputted camera pose should be okay. With colmap camera pose its just colours but no shape.
![my transform.json](https://github.com/user-attachments/assets/c8b0149b-a16c-4e86-9cad-62d7fc511ce3)
!colmap transforms.json](https://github.com/user-attachments/assets/60da07d4-677d-43c3-9728-618928558112)

Is it like that gsplat or nerf does not work for closed shapes like a tube. My data is a synthetic colon which is a tube like structure.

Thanks in advance

**Comment by maturk** [comment]
Can you show examples of what your images look like? Are images taken from outside or inside the tube? (Like is camera inside colon looking at the walls?)

**Comment by engs2570** [comment]
First of all many thanks for your help. The camera moves through the synthetic colon. Its for inside. Below are examples of first few frames. atm I am trying with 512 frames. Maybe I should try with less frames?
![image](https://github.com/user-attachments/assets/93c9aea8-b3f6-4587-a718-62fd347d025a)

**Comment by maturk** [comment]
Yes, this looks like a very very challenging scenario... GS struggles a lot with outward facing scenes with low texture. With very low texture, it becomes difficult to optimize due to ambiguities in multi-view consistency, which is why it looks like in your scene the Gaussians kind of explode and float around to wrong places. I suggest you try to add some regularization, like depth regularization, into the optimization. Since you mentioned your point cloud contains millions of points, this could give you good supervision signals to constrain the optimization. 

I don't really have any suggestions besides this, since gsplat is not really designed to tackle these kinds of scenes. Maybe you can refer to relevant research like [this](https://arxiv.org/pdf/2404.06128v1) for inspiration.
