### ISSUE TITLE
No module named 'gsplat.optimizers' when trying to run simple_trainer.py

### ISSUE THREAD

**Issue by felixniemeyer** [nerfstudio-project/gsplat#525]
I'm trying to run the simple_trainer.py but the module gsplat.optimizers cannot be found.

```
python simple_trainer.py default --data_dir ../../../sfm/kirche-col/dense --result_dir ./results/kirche-col
Traceback (most recent call last):
  File "/home/felix/davdev/splatting/repos/gsplat/examples/simple_trainer.py", line 43, in <module>
    from gsplat.optimizers import SelectiveAdam
ModuleNotFoundError: No module named 'gsplat.optimizers'
```

Maybe it moved somewhere else?

**Comment by felixniemeyer** [comment]
this is what there is: 
```
>>> import gsplat
>>> gsplat.
gsplat.DefaultStrategy(                     gsplat.rasterization(
gsplat.MCMCStrategy(                        gsplat.rasterization_2dgs(
gsplat.PngCompression(                      gsplat.rasterization_2dgs_inria_wrapper(
gsplat.Strategy()                           gsplat.rasterization_inria_wrapper(
gsplat.accumulate(                          gsplat.rasterize_to_indices_in_range(
gsplat.accumulate_2dgs(                     gsplat.rasterize_to_indices_in_range_2dgs(
gsplat.all                                  gsplat.rasterize_to_pixels(
gsplat.compression                          gsplat.rasterize_to_pixels_2dgs(
gsplat.cuda                                 gsplat.relocation
gsplat.distributed                          gsplat.rendering
gsplat.fully_fused_projection(              gsplat.spherical_harmonics(
gsplat.fully_fused_projection_2dgs(         gsplat.strategy
gsplat.isect_offset_encode(                 gsplat.utils
gsplat.isect_tiles(                         gsplat.version
gsplat.proj(                                gsplat.warnings
gsplat.quat_scale_to_covar_preci(           gsplat.world_to_cam(
```

**Comment by maturk** [comment]
@felixniemeyer, are you certain that you have the latest gsplat repo cloned? optimizers are found here https://github.com/nerfstudio-project/gsplat/tree/main/gsplat/optimizers

**Comment by maturk** [comment]
See this issue, it should fix it: https://github.com/nerfstudio-project/gsplat/issues/463

**Comment by felixniemeyer** [comment]
You're completely right: I was running the example code from the cloned repo, but had installed gsplat with `pip install gsplat` as instructed in the readme. 

I've built gsplat manually as you say and it's working now!

Thank you!

**Comment by halil-karabacak** [comment]
if you encpunter with glm issue, just dowloadn. set the value in the header file absolute and give another try because cmakelist includes doesnt seem to work.

**Comment by vipcxj** [comment]
@halil-karabacak Which package do i need to install with pip to solve the problem of not finding glm header files? I tried pyglm and pyopengl, neither of them worked

**Comment by halil-karabacak** [comment]
@vipcxj Problem lies in gsplat. find_package() in the  https://github.com/nerfstudio-project/gsplat/blob/main/gsplat/cuda/csrc/CMakeLists.txt  doesn't seem to work. Just replace with the absolute path of glm, instead of relative. For example, if you get error in this file https://github.com/nerfstudio-project/gsplat/blob/main/gsplat/cuda/include/types.cuh , replace the #include <glm/gtc/type_ptr.hpp> with the absolute path.

**Comment by vipcxj** [comment]
@halil-karabacak finally I download the repo of glm, and copy all include files to conda environemnt include dir. because glm is a head-only library, it's work through not perfact. I am using windows, so I can't just type `apt-get install libglm-dev` on ubuntu.

**Comment by halil-karabacak** [comment]
@vipcxj nice.
