### ISSUE TITLE
CUDA/v11.8 windows compile error

### ISSUE THREAD

**Issue by 3a1b2c3** [nerfstudio-project/gsplat#56]
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(338): error: expected an identifier       

    C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.8/include\cub/device/dispatch/dispatch_segmented_sort.cuh(379): error: expected a member name       

    3 errors detected in the compilation of "gsplat/cuda/csrc/bindings.cu".
    bindings.cu
    error: command 'C:\\Program Files\\NVIDIA GPU Computing Toolkit\\CUDA\\v11.8\\bin\\nvcc.exe' failed with exit code 2
    [end of output]

**Comment by maturk** [comment]
I think this is fixed in #54 . Feel free to open if issues persist after latest pulls.
