### ISSUE TITLE
Can gsplat supports depth & mask rendering later?

### ISSUE THREAD

**Issue by imlixinyang** [nerfstudio-project/gsplat#57]

**Comment by vye16** [comment]
Yes, you can pass in the depth or a label for each gaussian instead of
color, and rasterize the target image as usual.

**Comment by imlixinyang** [comment]
I've tried but "RasterizeGaussians" function seems to support only 3-channel colors now. @vye16

**Comment by imlixinyang** [comment]
I try to modify the file examples/simple_trainer.py:
`
out_img, out_depth = RasterizeGaussians.apply(
                xys,
                depths,
                radii,
                conics,
                num_tiles_hit,
                torch.cat([torch.sigmoid(self.rgbs), depths[..., None]], -1),
                opacity,
                self.H,
                self.W,
            ).split([3, 1], -1)
`
 and raise:
`
  File "./gsplat/gsplat/cuda/__init__.py", line 9, in call_cuda
    return getattr(_C, name)(*args, **kwargs)
RuntimeError: colors must have dimensions (N, 3)
`

**Comment by maturk** [comment]
Hi @imlixinyang , if you git pull the most recent version of gsplat, there is a python binding called NDRasterizeGaussians which allows you to render any N dimensional vector, not just 3 channel RGB. You can consider using this in simple_trainer instead of RasterizeGaussians.
