### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by dllu** [nerfstudio-project/gsplat#58]
Should probably add an apache license similar to the rest of the nerfstudio project.

For reference, the official gaussian splatting implementation has a [restrictive license that makes it hard to use commercially](https://github.com/graphdeco-inria/diff-gaussian-rasterization/blob/main/LICENSE.md).

**Comment by rosejn** [comment]
It was Apache licensed until this PR: https://github.com/nerfstudio-project/gsplat/pull/52

But there isn't any explanation...

**Comment by JohanVer** [comment]
Thanks for the great work! 
Is there any update on the licence? @liruilong940607

**Comment by machenmusik** [comment]
Looks like this merged commit https://github.com/nerfstudio-project/gsplat/tree/f6b07c8cda3530f0a9206b0a0a29215eb158c27f was intended to add Apache 2.0 LICENSE, but didn't

**Comment by vye16** [comment]
Hi all, we intend to make the license Apache. Please contact
***@***.*** for more details if needed.
