### ISSUE TITLE
video input

### ISSUE THREAD

**Issue by chris-aeviator** [nerfstudio-project/gsplat#62]
To follow up on the original implementation, how can I run gsplat with a video as input?

**Comment by maturk** [comment]
@chris-aeviator, this is only the backend CUDA kernels with python bindings. Full 3D training has not been implemented here, so video input is not supported. You can consider using the [Nerfstudio](https://github.com/nerfstudio-project/nerfstudio/pull/2521) PR that implements full 3D training using gsplat. Nerfstudio can then process your video inputs etc.

**Comment by chris-aeviator** [comment]
@maturk thanks for the ultra quick clarification, closing this
