### ISSUE TITLE
ask for help

### ISSUE THREAD

**Issue by zcdliuwei** [nerfstudio-project/gsplat#69]
thanks for your great work!
when I run python examples/simple_trainer.py, I received the following error report:
AttributeError: 'NoneType' object has no attribute 'project_gaussians_forward'

This is my Ubuntu server environment：
![image](https://github.com/nerfstudio-project/gsplat/assets/36565076/6c25de5d-9e86-43d1-b319-ce4a042a2136)
Looking forward to your reply

**Comment by hecodeit** [comment]
@zcdliuwei 
Did you solve the problem? Meeting the same here.

**Comment by Linusnie** [comment]
in my case the problem was solved by installing from source with `pip install git+https://github.com/nerfstudio-project/gsplat.git`
