### ISSUE TITLE
Negative coordinates of gaussian centers

### ISSUE THREAD

**Issue by saswat0** [nerfstudio-project/gsplat#77]
The following [line](https://github.com/nerfstudio-project/gsplat/blob/3f4f386aab71b127cf4174d5ff978187c006bd1a/examples/simple_trainer.py#L90) returns the centers of the gaussian.
```
xys, depths, radii, conics, num_tiles_hit, cov3d = ProjectGaussians.apply(
                self.means,
                self.scales,
                1,
                self.quats,
                self.viewmat,
                self.viewmat,
                self.focal,
                self.focal,
                self.W / 2,
                self.H / 2,
                self.H,
                self.W,
                self.tile_bounds,
            )
```

But when I try to find the bounds of this tensor, I get negative values.
```
print(torch.min(xys[:, 0]), torch.max(xys[:, 0]))
print(torch.min(xys[:, 1]), torch.max(xys[:, 1]))
```

How can I deal with negative pixel values? Should I just clamp at 0?
Am I doing it wrong? Are the coordinates (`xys`) returned not representative of the actual centres of the gaussian in the pixel space?

**Comment by maturk** [comment]
@saswat0 yeah the xys output of `ProjectGaussians` projects all gaussians to the image plane and it is possible that gaussian centers lie beyong the bounds of the (H,W) image. The rasterizer correctly discards the negative and beyond (H,W) gaussian centers when we map gaussians to intersects in bins before sorting. More specifically [here]( https://github.com/nerfstudio-project/gsplat/blob/e7513c833a08ca73ce20f4f6de2ff2f74b013e83/gsplat/cuda/csrc/helpers.cuh#L11C1-L11C1)

**Comment by saswat0** [comment]
Thanks @maturk 
If I had to find which points a gaussian covers (or vice versa, which gaussians contribute to a point), would you recommend taking the splats? Or is there a way to get a mapping directly from the source?

**Comment by maturk** [comment]
closing this one in favour of the more recent #87
