### ISSUE TITLE
Is this support ray-based rendering of 3dgs? or just image based rasterizer for nerf community?

### ISSUE THREAD

**Issue by zeyutt** [nerfstudio-project/gsplat#79]
Is this support ray-based rendering of 3dgs? or just image based rasterizer for nerf community?
if it support ray-bundles rendering, highly recommend authors/DMs to highlight this feature for more attention. 
I am quite sure this will achieve more interesting results than the original ones. :>

**Comment by maturk** [comment]
@zeyutt This repo only supports rasterization! :) ray-tracing gaussians is interesting too but probably out of the scope of this repo for now.

**Comment by pknmax** [comment]
@maturk is anyone working in this direction?
how one can achieve this? can you suggest some rough steps and guidelines?

**Comment by maturk** [comment]
@pknmax not that I know of. Ray tracing gaussians is quite different from the 3DGS splatting/rasterization method proposed by inria. If you are interested in this direction, you could check out Leonid's [paper](https://leonidk.com/fmb-plus/) about a cool ray-traced gaussian renderer.

**Comment by maturk** [comment]
@pknmax not that I know of. Ray tracing gaussians is quite different from the 3DGS splatting/rasterization method proposed by inria. If you are interested in this direction, you could check out Leonid's [paper](https://leonidk.com/fmb-plus/) about a cool ray-traced gaussian renderer.

**Comment by brentyi** [comment]
also relevant: https://github.com/leonidk/ns-fmb
