### ISSUE TITLE
Does `NDRasterizeGaussians` support ND?

### ISSUE THREAD

**Issue by Xanthorapedia** [nerfstudio-project/gsplat#83]
It seems like ND rasterization is restricted to 3D:
https://github.com/nerfstudio-project/gsplat/blob/dbd0cab31d0ad2e811c8b7511fc03dc65dcecf6a/gsplat/nd_rasterize.py#L64-L65

**Comment by filick** [comment]
In my experiment, it works well if I skip this check. Can we just delect the second condition in Line 64?
