### ISSUE TITLE
Training for RGBA images

### ISSUE THREAD

**Issue by hardikdava** [nerfstudio-project/gsplat#89]
Thank you for your amazing work. 

Is it possible to train for RGBA images? e.g. with alpha channel. 
If not how can it be done?

**Comment by ivanpuhachov** [comment]
It's an old issue but I was doing the same recently.

* `rasterize_gaussians` returns accumulated alpha (`1 - final_Ts`) if you call it with `return_alpha=True`
* see `splatfacto` training for more examples https://github.com/nerfstudio-project/nerfstudio/blob/5491df92d9f6a47c86f7e1ecb4e986ae1e1f5632/nerfstudio/models/splatfacto.py#L776 
* see discussions on alpha carving in splatfacto https://github.com/nerfstudio-project/nerfstudio/pull/2889

I think this issue can be closed.
