### ISSUE TITLE
Unreasonably slow forward pass

### ISSUE THREAD

**Issue by kwea123** [nerfstudio-project/gsplat#92]
I tried `python examples/simple_trainer.py` with
```
height: int = 1024,
width: int = 1024,
num_points: int = 100000,
```
which is closer to a 3D setup, and the time is very slow (1000 steps)
```
Total(s):
Project: 0.510, Rasterize: 13.616, Backward: 2.199
```
what looks particularly concerning to me is that forward pass is 6X slower than backward...

**Comment by drx-code** [comment]
Did you slove that problem?
