### ISSUE TITLE
Question about the derivation of the view matrix gradient in paper

### ISSUE THREAD

**Issue by QitaoZhao** [nerfstudio-project/gsplat#98]
Hi, team; thanks for your contributions! I'm recently reading your paper ([Mathematical Supplement for the gsplat Library](https://arxiv.org/pdf/2312.02121.pdf)) and have one question about the derivation of the view matrix gradient.

I understand the gradient of the view matrix ($\frac{\partial L}{\partial T_{CW}}$) can flow from the gradient of camera space 3D means ($\frac{\partial L}{\partial t}$), which is given by equation (28) in your paper. As the 2D covariance is parameterized as $\Sigma'=JR_{CW}\Sigma\ R_{CW}^{T}J^{T}$, I wonder if the gradient of the view matrix can also flow from $R_{CW}$, a part of the view matrix. It seems that the contribution of $J$ to $\frac{\partial L}{\partial T_{CW}}$ has been counted in the form of $\frac{\partial L_{\Sigma'}}{\partial J}\frac{\partial J}{\partial t}$, but the contribution of $R_{CW}$ in $\Sigma'$ has not. Should we add this term ($\frac{\partial L}{\partial \Sigma'}\frac{\partial \Sigma'}{\partial R_{CW}}$) to $\frac{\partial L}{\partial T_{CW}}$? Any explanation or correction is highly appreciated!
<img width="1346" alt="Screen Shot 2024-01-06 at 00 56 12" src="https://github.com/nerfstudio-project/gsplat/assets/68940825/b7e31166-0708-4e5f-9024-5e591d5a000e">

**Comment by QitaoZhao** [comment]
By the way, do you implement the view matrix gradient in your code?

**Comment by vye16** [comment]
Hi Qitao, great catch! Yes, there should also be a contribution to R_cw
from dL/dSigma', that's currently missing in the derivation. In the code,
the view matrix gradients are not implemented yet, but we hope to add this
in soon.
